[package]
name = "openxrvulkano"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.37"
vulkano = { version = "0.34.1", features = ["document_unchecked"] }
vulkano-shaders = "0.34.0"
openxr = {version = "0.19.0", features = ["static"]}
